FROM ubuntu:24.04

# Install Cross-Compiler Toolchain & Utils
# gcc-multilib allows building 32-bit (i686) binaries on x86_64
RUN apt-get update && apt-get install -y \
    build-essential \
    bison \
    flex \
    libgmp3-dev \
    libmpc-dev \
    libmpfr-dev \
    texinfo \
    xorriso \
    grub-pc-bin \
    grub-common \
    gcc-multilib \
    g++-multilib \
    nasm \
    make \
    qemu-system-x86

WORKDIR /harmony
COPY . /harmony

# Set executable permissions
RUN chmod +x deploy/build_iso.sh run_os.sh

# Default command: Build the ISO
CMD ["./deploy/build_iso.sh"]
